# render.yaml

services:
  # --- Backend (Express API) ---
  - type: web
    name: myapp-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js   # or "npm start" if that's what you use
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false     # You'll paste Atlas URI in Render dashboard
      - key: CORS_ORIGIN
        sync: false     # We'll add frontend URL here after deploy

  # --- Frontend (React + Vite) ---
  - type: web
    name: myapp-web
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false     # We'll add backend URL here after deploy
